
platform :ios, '8.0'
use_frameworks!

target 'OMNI' do

    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'SDAutoLayout'
    pod 'CocoaAsyncSocket'
    pod 'ReactiveCocoa'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    pod 'MMDrawerController'
    pod 'YYCache'
end