
platform :ios, '8.0'
use_frameworks!

target 'OMNI' do

    pod 'MBProgressHUD'
    pod 'SDAutoLayout'
    pod 'CocoaAsyncSocket'
    pod 'ReactiveCocoa'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    
end